In [4]:
import pandas as pd

In [22]:
df = pd.read_csv('creditcard.csv')

In [23]:
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [24]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [25]:
df.shape

(284807, 31)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [27]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [28]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(1081)

In [30]:
df = df.drop_duplicates()

In [31]:
df.duplicated().sum()   # ab 0 aana chahiye

np.int64(0)

In [32]:
df.shape

(283726, 31)

In [33]:
X = df.drop(columns=['Class'])
y = df['Class']

print(X.shape)
print(y.shape)

(283726, 30)
(283726,)

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
print(y.isnull().sum())
print(X.isnull().sum().sum())

0
0

In [36]:
df[df['Class'].isnull()]

Empty DataFrame
Columns: [Time, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21, V22, V23, V24, V25, V26, V27, V28, Amount, Class]
Index: []

[0 rows x 31 columns]

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [38]:
print(y_train.value_counts())
print(y_test.value_counts())

Class
0    226602
1       378
Name: count, dtype: int64
Class
0    56651
1       95
Name: count, dtype: int64

In [39]:
from sklearn.preprocessing import StandardScaler

In [41]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [42]:
print(X_train_scaled.mean())
print(X_train_scaled.std())

-3.6500697413705035e-18
1.0000000000000004

In [43]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.13/dist-packages (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (2.1.3)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (3.6.0)

In [44]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

print(y_train_smote.value_counts())

Class
0    226602
1    226602
Name: count, dtype: int64

In [45]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Input(shape=(X_train_smote.shape[1],)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(
    X_train_smote, y_train_smote,
    validation_split=0.2,
    epochs=50,
    batch_size=512
)

Epoch 1/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 17s 14ms/step - accuracy: 0.9761 - loss: 0.0703 - val_accuracy: 0.9981 - val_loss: 0.0184
Epoch 2/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9980 - loss: 0.0107 - val_accuracy: 1.0000 - val_loss: 0.0070
Epoch 3/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9989 - loss: 0.0056 - val_accuracy: 1.0000 - val_loss: 0.0026
Epoch 4/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9993 - loss: 0.0040 - val_accuracy: 1.0000 - val_loss: 0.0022
Epoch 5/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9994 - loss: 0.0031 - val_accuracy: 1.0000 - val_loss: 0.0010
Epoch 6/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9995 - loss: 0.0025 - val_accuracy: 1.0000 - val_loss: 5.1499e-04
Epoch 7/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9996 - loss: 0.0021 - val_accuracy: 1.0000 - val_loss: 6.4476e-04
Epoch 8/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9997 - loss: 0.0017 - val_accuracy: 1.0000 - val_loss: 8.0246e-04
Epoch 9/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9997 - loss: 0.0017 - val_accuracy: 1.0000 - val_loss: 4.9600e-04
Epoch 10/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9997 - loss: 0.0014 - val_accuracy: 1.0000 - val_loss: 0.0020
Epoch 11/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 1.0000 - val_loss: 5.3151e-04
Epoch 12/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9997 - loss: 0.0015 - val_accuracy: 1.0000 - val_loss: 4.0959e-04
Epoch 13/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 9.9242e-04 - val_accuracy: 1.0000 - val_loss: 1.7149e-04
Epoch 14/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9998 - loss: 8.0211e-04 - val_accuracy: 1.0000 - val_loss: 3.3936e-04
Epoch 15/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9998 - loss: 8.9329e-04 - val_accuracy: 1.0000 - val_loss: 6.0232e-05
Epoch 16/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 9.5732e-04 - val_accuracy: 1.0000 - val_loss: 4.0225e-04
Epoch 17/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 5.5992e-04 - val_accuracy: 1.0000 - val_loss: 9.4510e-05
Epoch 18/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 6.8689e-04 - val_accuracy: 1.0000 - val_loss: 3.3042e-05
Epoch 19/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9998 - loss: 0.0010 - val_accuracy: 1.0000 - val_loss: 1.0690e-04
Epoch 20/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 9.1745e-04 - val_accuracy: 1.0000 - val_loss: 4.2972e-04
Epoch 21/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 4.0243e-04 - val_accuracy: 1.0000 - val_loss: 1.5812e-04
Epoch 22/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 3.6670e-04 - val_accuracy: 0.9986 - val_loss: 0.0028
Epoch 23/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 5.2019e-04 - val_accuracy: 1.0000 - val_loss: 7.6967e-05
Epoch 24/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 8.0112e-04 - val_accuracy: 1.0000 - val_loss: 2.4925e-04
Epoch 25/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 6.1106e-04 - val_accuracy: 1.0000 - val_loss: 1.8304e-04
Epoch 26/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 3.5906e-04 - val_accuracy: 1.0000 - val_loss: 1.4633e-04
Epoch 27/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 1.0000 - val_loss: 9.8776e-05
Epoch 28/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 2.9195e-04 - val_accuracy: 1.0000 - val_loss: 3.1896e-05
Epoch 29/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 5.2209e-04 - val_accuracy: 1.0000 - val_loss: 6.2576e-05
Epoch 30/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 6.6014e-04 - val_accuracy: 1.0000 - val_loss: 4.6575e-04
Epoch 31/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 2.6848e-04 - val_accuracy: 1.0000 - val_loss: 2.6142e-05
Epoch 32/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 3.3621e-04 - val_accuracy: 1.0000 - val_loss: 8.7971e-05
Epoch 33/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 7.9055e-04 - val_accuracy: 0.9997 - val_loss: 0.0011
Epoch 34/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 4.0008e-04 - val_accuracy: 1.0000 - val_loss: 2.7236e-05
Epoch 35/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 2.6813e-04 - val_accuracy: 1.0000 - val_loss: 4.1466e-05
Epoch 36/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 3.4480e-04 - val_accuracy: 1.0000 - val_loss: 5.2914e-04
Epoch 37/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 3.1382e-04 - val_accuracy: 1.0000 - val_loss: 3.4860e-05
Epoch 38/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 2.3927e-04 - val_accuracy: 1.0000 - val_loss: 3.7852e-05
Epoch 39/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.4987e-04 - val_accuracy: 1.0000 - val_loss: 4.3085e-05
Epoch 40/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 1.0000 - val_loss: 2.9454e-04
Epoch 41/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 2.7786e-04 - val_accuracy: 1.0000 - val_loss: 1.1271e-04
Epoch 42/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 2.0675e-04 - val_accuracy: 1.0000 - val_loss: 3.8994e-04
Epoch 43/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 3.0263e-04 - val_accuracy: 1.0000 - val_loss: 3.1954e-05
Epoch 44/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.5100e-04 - val_accuracy: 0.9992 - val_loss: 0.0025
Epoch 45/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 3.2392e-04 - val_accuracy: 1.0000 - val_loss: 6.0051e-05
Epoch 46/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9998 - loss: 9.6061e-04 - val_accuracy: 1.0000 - val_loss: 1.2145e-04
Epoch 47/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 1.0000 - loss: 1.7614e-04 - val_accuracy: 1.0000 - val_loss: 9.0395e-05
Epoch 48/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 2.1823e-04 - val_accuracy: 1.0000 - val_loss: 7.9451e-05
Epoch 49/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 3.6169e-04 - val_accuracy: 1.0000 - val_loss: 3.7599e-05
Epoch 50/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 4.1245e-04 - val_accuracy: 1.0000 - val_loss: 3.2494e-05

In [46]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

# Pehle train ko train+validation mein split karein (SMOTE se pehle!)
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train_scaled, y_train, test_size=0.2, random_state=42, stratify=y_train
)

# Ab SMOTE SIRF X_tr, y_tr par apply karein (validation ko chuein bhi nahi)
smote = SMOTE(random_state=42)
X_tr_smote, y_tr_smote = smote.fit_resample(X_tr, y_tr)

# Model training mein validation_split ki jagah validation_data use karein
history = model.fit(
    X_tr_smote, y_tr_smote,
    validation_data=(X_val, y_val),   # ye original imbalanced validation hai — realistic
    epochs=50,
    batch_size=512
)

Epoch 1/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 4.3639e-04 - val_accuracy: 0.9999 - val_loss: 3.4892e-04
Epoch 2/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.8494e-04 - val_accuracy: 0.9999 - val_loss: 2.1822e-04
Epoch 3/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.5919e-04 - val_accuracy: 1.0000 - val_loss: 1.9204e-04
Epoch 4/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.8139e-04 - val_accuracy: 0.9999 - val_loss: 1.9023e-04
Epoch 5/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.8498e-04 - val_accuracy: 1.0000 - val_loss: 1.9249e-04
Epoch 6/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9999 - loss: 8.7586e-04 - val_accuracy: 0.9998 - val_loss: 5.7071e-04
Epoch 7/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 2.7940e-04 - val_accuracy: 0.9998 - val_loss: 7.9722e-04
Epoch 8/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.4439e-04 - val_accuracy: 0.9998 - val_loss: 7.9925e-04
Epoch 9/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.4520e-04 - val_accuracy: 0.9998 - val_loss: 7.6963e-04
Epoch 10/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 2.3652e-04 - val_accuracy: 0.9998 - val_loss: 8.3900e-04
Epoch 11/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.4180e-04 - val_accuracy: 0.9998 - val_loss: 7.3822e-04
Epoch 12/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 9.7712e-05 - val_accuracy: 0.9998 - val_loss: 7.5131e-04
Epoch 13/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 4.4920e-04 - val_accuracy: 0.9993 - val_loss: 0.0037
Epoch 14/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 5.3999e-04 - val_accuracy: 0.9997 - val_loss: 0.0023
Epoch 15/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.3291e-04 - val_accuracy: 0.9998 - val_loss: 0.0025
Epoch 16/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.0606e-04 - val_accuracy: 0.9997 - val_loss: 0.0024
Epoch 17/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 6.6671e-04 - val_accuracy: 0.9995 - val_loss: 0.0025
Epoch 18/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.7354e-04 - val_accuracy: 0.9998 - val_loss: 0.0017
Epoch 19/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 9.8510e-05 - val_accuracy: 0.9998 - val_loss: 0.0016
Epoch 20/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 9.1917e-05 - val_accuracy: 0.9998 - val_loss: 0.0018
Epoch 21/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 6.6383e-04 - val_accuracy: 0.9998 - val_loss: 0.0022
Epoch 22/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 3.4234e-04 - val_accuracy: 0.9997 - val_loss: 0.0024
Epoch 23/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.0800e-04 - val_accuracy: 0.9997 - val_loss: 0.0024
Epoch 24/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.0096e-04 - val_accuracy: 0.9997 - val_loss: 0.0024
Epoch 25/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 1.0000 - loss: 8.9186e-05 - val_accuracy: 0.9997 - val_loss: 0.0025
Epoch 26/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.1607e-04 - val_accuracy: 0.9997 - val_loss: 0.0024
Epoch 27/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 3.5811e-04 - val_accuracy: 0.9995 - val_loss: 0.0043
Epoch 28/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 2.3279e-04 - val_accuracy: 0.9997 - val_loss: 0.0040
Epoch 29/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.4466e-04 - val_accuracy: 0.9997 - val_loss: 0.0039
Epoch 30/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.0325e-04 - val_accuracy: 0.9997 - val_loss: 0.0038
Epoch 31/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.5739e-04 - val_accuracy: 0.9994 - val_loss: 0.0046
Epoch 32/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 0.0013 - val_accuracy: 0.9996 - val_loss: 0.0039
Epoch 33/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.0920e-04 - val_accuracy: 0.9997 - val_loss: 0.0041
Epoch 34/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9999 - loss: 2.2843e-04 - val_accuracy: 0.9997 - val_loss: 0.0040
Epoch 35/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 9.6735e-05 - val_accuracy: 0.9997 - val_loss: 0.0040
Epoch 36/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 1.0000 - loss: 7.1790e-05 - val_accuracy: 0.9997 - val_loss: 0.0041
Epoch 37/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 1.0000 - loss: 1.1465e-04 - val_accuracy: 0.9997 - val_loss: 0.0041
Epoch 38/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 8.6084e-05 - val_accuracy: 0.9997 - val_loss: 0.0043
Epoch 39/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.0790e-04 - val_accuracy: 0.9997 - val_loss: 0.0043
Epoch 40/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9999 - loss: 7.9039e-04 - val_accuracy: 0.9997 - val_loss: 0.0039
Epoch 41/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 2.0944e-04 - val_accuracy: 0.9997 - val_loss: 0.0036
Epoch 42/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 3.4174e-04 - val_accuracy: 0.9996 - val_loss: 0.0041
Epoch 43/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 1.0000 - loss: 1.2522e-04 - val_accuracy: 0.9997 - val_loss: 0.0040
Epoch 44/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.7299e-04 - val_accuracy: 0.9997 - val_loss: 0.0043
Epoch 45/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.3727e-04 - val_accuracy: 0.9997 - val_loss: 0.0043
Epoch 46/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.5865e-04 - val_accuracy: 0.9996 - val_loss: 0.0043
Epoch 47/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 1.1919e-04 - val_accuracy: 0.9997 - val_loss: 0.0043
Epoch 48/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 9.0495e-05 - val_accuracy: 0.9997 - val_loss: 0.0042
Epoch 49/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.4695e-04 - val_accuracy: 0.9997 - val_loss: 0.0042
Epoch 50/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.0370e-04 - val_accuracy: 0.9996 - val_loss: 0.0042

In [47]:
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                               f1_score, confusion_matrix, classification_report)

# Predictions - probabilities milengi (0 se 1 ke beech)
y_pred_proba = model.predict(X_test_scaled)

# 0.5 threshold laga kar 0/1 mein convert karein
y_pred = (y_pred_proba > 0.5).astype(int)

# Metrics nikalein
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

1774/1774 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
Accuracy: 0.9992951045007578
Precision: 0.7894736842105263
Recall: 0.7894736842105263
F1 Score: 0.7894736842105263

Confusion Matrix:
[[56631    20]
 [   20    75]]

In [48]:
model2 = keras.Sequential([
    keras.layers.Input(shape=(X_tr_smote.shape[1],)),
    keras.layers.Dense(64, activation='tanh'),
    keras.layers.Dense(32, activation='tanh'),
    keras.layers.Dense(1, activation='sigmoid')   # output layer hamesha sigmoid rahega (binary classification)
])

model2.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

history2 = model2.fit(
    X_tr_smote, y_tr_smote,
    validation_data=(X_val, y_val),
    epochs=50,
    batch_size=512
)

Epoch 1/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9210 - loss: 0.2298 - val_accuracy: 0.9714 - val_loss: 0.1524
Epoch 2/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9508 - loss: 0.1256 - val_accuracy: 0.9693 - val_loss: 0.1171
Epoch 3/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9537 - loss: 0.1106 - val_accuracy: 0.9680 - val_loss: 0.1050
Epoch 4/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9567 - loss: 0.1026 - val_accuracy: 0.9676 - val_loss: 0.0991
Epoch 5/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9598 - loss: 0.0965 - val_accuracy: 0.9672 - val_loss: 0.0948
Epoch 6/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9627 - loss: 0.0911 - val_accuracy: 0.9686 - val_loss: 0.0891
Epoch 7/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9649 - loss: 0.0862 - val_accuracy: 0.9691 - val_loss: 0.0856
Epoch 8/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9670 - loss: 0.0816 - val_accuracy: 0.9705 - val_loss: 0.0815
Epoch 9/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9687 - loss: 0.0773 - val_accuracy: 0.9724 - val_loss: 0.0763
Epoch 10/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9703 - loss: 0.0732 - val_accuracy: 0.9739 - val_loss: 0.0719
Epoch 11/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9718 - loss: 0.0694 - val_accuracy: 0.9744 - val_loss: 0.0698
Epoch 12/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9738 - loss: 0.0658 - val_accuracy: 0.9748 - val_loss: 0.0680
Epoch 13/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9757 - loss: 0.0623 - val_accuracy: 0.9776 - val_loss: 0.0627
Epoch 14/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9773 - loss: 0.0591 - val_accuracy: 0.9790 - val_loss: 0.0592
Epoch 15/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9786 - loss: 0.0561 - val_accuracy: 0.9796 - val_loss: 0.0581
Epoch 16/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9802 - loss: 0.0534 - val_accuracy: 0.9811 - val_loss: 0.0554
Epoch 17/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9816 - loss: 0.0507 - val_accuracy: 0.9824 - val_loss: 0.0528
Epoch 18/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9835 - loss: 0.0483 - val_accuracy: 0.9836 - val_loss: 0.0502
Epoch 19/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9850 - loss: 0.0460 - val_accuracy: 0.9841 - val_loss: 0.0488
Epoch 20/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9861 - loss: 0.0439 - val_accuracy: 0.9846 - val_loss: 0.0478
Epoch 21/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9871 - loss: 0.0420 - val_accuracy: 0.9857 - val_loss: 0.0451
Epoch 22/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9879 - loss: 0.0401 - val_accuracy: 0.9864 - val_loss: 0.0433
Epoch 23/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9885 - loss: 0.0384 - val_accuracy: 0.9865 - val_loss: 0.0427
Epoch 24/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9893 - loss: 0.0369 - val_accuracy: 0.9872 - val_loss: 0.0406
Epoch 25/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9900 - loss: 0.0354 - val_accuracy: 0.9880 - val_loss: 0.0385
Epoch 26/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9905 - loss: 0.0340 - val_accuracy: 0.9877 - val_loss: 0.0386
Epoch 27/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9909 - loss: 0.0327 - val_accuracy: 0.9878 - val_loss: 0.0382
Epoch 28/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9914 - loss: 0.0315 - val_accuracy: 0.9886 - val_loss: 0.0361
Epoch 29/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9918 - loss: 0.0304 - val_accuracy: 0.9889 - val_loss: 0.0352
Epoch 30/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9922 - loss: 0.0293 - val_accuracy: 0.9889 - val_loss: 0.0351
Epoch 31/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9925 - loss: 0.0284 - val_accuracy: 0.9896 - val_loss: 0.0332
Epoch 32/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9928 - loss: 0.0274 - val_accuracy: 0.9901 - val_loss: 0.0316
Epoch 33/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9931 - loss: 0.0266 - val_accuracy: 0.9902 - val_loss: 0.0310
Epoch 34/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9934 - loss: 0.0258 - val_accuracy: 0.9903 - val_loss: 0.0309
Epoch 35/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9936 - loss: 0.0250 - val_accuracy: 0.9904 - val_loss: 0.0301
Epoch 36/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9939 - loss: 0.0243 - val_accuracy: 0.9911 - val_loss: 0.0285
Epoch 37/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9941 - loss: 0.0236 - val_accuracy: 0.9910 - val_loss: 0.0286
Epoch 38/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9943 - loss: 0.0230 - val_accuracy: 0.9913 - val_loss: 0.0277
Epoch 39/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9944 - loss: 0.0224 - val_accuracy: 0.9912 - val_loss: 0.0277
Epoch 40/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9945 - loss: 0.0218 - val_accuracy: 0.9919 - val_loss: 0.0262
Epoch 41/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9947 - loss: 0.0212 - val_accuracy: 0.9920 - val_loss: 0.0258
Epoch 42/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9948 - loss: 0.0207 - val_accuracy: 0.9920 - val_loss: 0.0258
Epoch 43/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9950 - loss: 0.0202 - val_accuracy: 0.9922 - val_loss: 0.0254
Epoch 44/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9951 - loss: 0.0198 - val_accuracy: 0.9924 - val_loss: 0.0244
Epoch 45/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9952 - loss: 0.0193 - val_accuracy: 0.9928 - val_loss: 0.0234
Epoch 46/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9954 - loss: 0.0189 - val_accuracy: 0.9925 - val_loss: 0.0241
Epoch 47/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9955 - loss: 0.0185 - val_accuracy: 0.9925 - val_loss: 0.0240
Epoch 48/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9956 - loss: 0.0181 - val_accuracy: 0.9930 - val_loss: 0.0227
Epoch 49/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9957 - loss: 0.0177 - val_accuracy: 0.9929 - val_loss: 0.0228
Epoch 50/50
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9958 - loss: 0.0173 - val_accuracy: 0.9933 - val_loss: 0.0218

In [49]:
y_pred_proba2 = model2.predict(X_test_scaled)
y_pred2 = (y_pred_proba2 > 0.5).astype(int)

print("Model 2 (Tanh + SGD)")
print("Accuracy:", accuracy_score(y_test, y_pred2))
print("Precision:", precision_score(y_test, y_pred2))
print("Recall:", recall_score(y_test, y_pred2))
print("F1 Score:", f1_score(y_test, y_pred2))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred2))

1774/1774 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
Model 2 (Tanh + SGD)
Accuracy: 0.9928629330701724
Precision: 0.1716101694915254
Recall: 0.8526315789473684
F1 Score: 0.2857142857142857

Confusion Matrix:
[[56260   391]
 [   14    81]]

In [50]:
model3 = keras.Sequential([
    keras.layers.Input(shape=(X_tr_smote.shape[1],)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model3.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

history3 = model3.fit(
    X_tr_smote, y_tr_smote,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=512
)

Epoch 1/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9908 - loss: 0.0276 - val_accuracy: 0.9970 - val_loss: 0.0109
Epoch 2/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9989 - loss: 0.0051 - val_accuracy: 0.9991 - val_loss: 0.0057
Epoch 3/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9993 - loss: 0.0033 - val_accuracy: 0.9991 - val_loss: 0.0069
Epoch 4/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9994 - loss: 0.0025 - val_accuracy: 0.9994 - val_loss: 0.0064
Epoch 5/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9996 - loss: 0.0018 - val_accuracy: 0.9994 - val_loss: 0.0068
Epoch 6/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9997 - loss: 0.0014 - val_accuracy: 0.9993 - val_loss: 0.0079
Epoch 7/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9997 - loss: 0.0013 - val_accuracy: 0.9991 - val_loss: 0.0091
Epoch 8/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 0.9986 - val_loss: 0.0109
Epoch 9/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9997 - loss: 0.0013 - val_accuracy: 0.9993 - val_loss: 0.0085
Epoch 10/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9993 - val_loss: 0.0082
Epoch 11/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9990 - val_loss: 0.0104
Epoch 12/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9997 - loss: 0.0012 - val_accuracy: 0.9994 - val_loss: 0.0084
Epoch 13/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9997 - loss: 0.0013 - val_accuracy: 0.9994 - val_loss: 0.0085
Epoch 14/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9993 - val_loss: 0.0093
Epoch 15/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 9.1839e-04 - val_accuracy: 0.9993 - val_loss: 0.0092
Epoch 16/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 9.8277e-04 - val_accuracy: 0.9994 - val_loss: 0.0089
Epoch 17/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9998 - loss: 9.7578e-04 - val_accuracy: 0.9995 - val_loss: 0.0093
Epoch 18/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 8.6387e-04 - val_accuracy: 0.9994 - val_loss: 0.0091
Epoch 19/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 8.0897e-04 - val_accuracy: 0.9993 - val_loss: 0.0102
Epoch 20/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9998 - loss: 9.3256e-04 - val_accuracy: 0.9993 - val_loss: 0.0104
Epoch 21/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 8.1163e-04 - val_accuracy: 0.9994 - val_loss: 0.0105
Epoch 22/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9997 - loss: 0.0013 - val_accuracy: 0.9994 - val_loss: 0.0103
Epoch 23/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9998 - loss: 8.1936e-04 - val_accuracy: 0.9993 - val_loss: 0.0104
Epoch 24/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 8.0074e-04 - val_accuracy: 0.9993 - val_loss: 0.0110
Epoch 25/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9998 - loss: 7.1475e-04 - val_accuracy: 0.9992 - val_loss: 0.0111
Epoch 26/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9998 - loss: 6.8007e-04 - val_accuracy: 0.9993 - val_loss: 0.0116
Epoch 27/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 8.7867e-04 - val_accuracy: 0.9994 - val_loss: 0.0110
Epoch 28/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 8.4204e-04 - val_accuracy: 0.9995 - val_loss: 0.0106
Epoch 29/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 7.7511e-04 - val_accuracy: 0.9994 - val_loss: 0.0109
Epoch 30/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9994 - val_loss: 0.0115
Epoch 31/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 0.0010 - val_accuracy: 0.9995 - val_loss: 0.0117
Epoch 32/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 7.3778e-04 - val_accuracy: 0.9994 - val_loss: 0.0122
Epoch 33/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9999 - loss: 6.3814e-04 - val_accuracy: 0.9993 - val_loss: 0.0122
Epoch 34/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9999 - loss: 7.8046e-04 - val_accuracy: 0.9995 - val_loss: 0.0134
Epoch 35/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 7.5897e-04 - val_accuracy: 0.9994 - val_loss: 0.0129
Epoch 36/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9998 - loss: 7.8237e-04 - val_accuracy: 0.9995 - val_loss: 0.0128
Epoch 37/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9999 - loss: 6.9224e-04 - val_accuracy: 0.9994 - val_loss: 0.0132
Epoch 38/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 6.3752e-04 - val_accuracy: 0.9994 - val_loss: 0.0133
Epoch 39/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 8.6312e-04 - val_accuracy: 0.9995 - val_loss: 0.0132
Epoch 40/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 5.5153e-04 - val_accuracy: 0.9994 - val_loss: 0.0137
Epoch 41/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9999 - loss: 4.7441e-04 - val_accuracy: 0.9995 - val_loss: 0.0132
Epoch 42/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 6.0769e-04 - val_accuracy: 0.9995 - val_loss: 0.0135
Epoch 43/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 5.8673e-04 - val_accuracy: 0.9992 - val_loss: 0.0137
Epoch 44/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9999 - loss: 4.1430e-04 - val_accuracy: 0.9996 - val_loss: 0.0134
Epoch 45/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9999 - loss: 4.9740e-04 - val_accuracy: 0.9995 - val_loss: 0.0137
Epoch 46/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9998 - loss: 5.3314e-04 - val_accuracy: 0.9994 - val_loss: 0.0143
Epoch 47/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 5.3797e-04 - val_accuracy: 0.9995 - val_loss: 0.0140
Epoch 48/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9999 - loss: 4.6223e-04 - val_accuracy: 0.9995 - val_loss: 0.0144
Epoch 49/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 5.8383e-04 - val_accuracy: 0.9994 - val_loss: 0.0146
Epoch 50/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 4.8506e-04 - val_accuracy: 0.9995 - val_loss: 0.0143
Epoch 51/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 2.8620e-04 - val_accuracy: 0.9995 - val_loss: 0.0146
Epoch 52/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9999 - loss: 5.9822e-04 - val_accuracy: 0.9995 - val_loss: 0.0143
Epoch 53/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 3.4351e-04 - val_accuracy: 0.9995 - val_loss: 0.0141
Epoch 54/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 5.3911e-04 - val_accuracy: 0.9994 - val_loss: 0.0143
Epoch 55/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.9999 - loss: 3.8601e-04 - val_accuracy: 0.9994 - val_loss: 0.0149
Epoch 56/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9999 - loss: 3.8518e-04 - val_accuracy: 0.9995 - val_loss: 0.0146
Epoch 57/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 2.1645e-04 - val_accuracy: 0.9995 - val_loss: 0.0149
Epoch 58/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 3.0682e-04 - val_accuracy: 0.9995 - val_loss: 0.0153
Epoch 59/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 1.0000 - loss: 2.7146e-04 - val_accuracy: 0.9995 - val_loss: 0.0147
Epoch 60/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 2.8923e-04 - val_accuracy: 0.9995 - val_loss: 0.0143
Epoch 61/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 2.3891e-04 - val_accuracy: 0.9995 - val_loss: 0.0166
Epoch 62/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9998 - loss: 9.1885e-04 - val_accuracy: 0.9991 - val_loss: 0.0163
Epoch 63/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9999 - loss: 3.5879e-04 - val_accuracy: 0.9995 - val_loss: 0.0155
Epoch 64/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 4.8675e-04 - val_accuracy: 0.9995 - val_loss: 0.0155
Epoch 65/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 3.7352e-04 - val_accuracy: 0.9994 - val_loss: 0.0154
Epoch 66/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9999 - loss: 3.3508e-04 - val_accuracy: 0.9994 - val_loss: 0.0164
Epoch 67/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 2.9664e-04 - val_accuracy: 0.9995 - val_loss: 0.0165
Epoch 68/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 2.6837e-04 - val_accuracy: 0.9994 - val_loss: 0.0167
Epoch 69/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9999 - loss: 4.1647e-04 - val_accuracy: 0.9995 - val_loss: 0.0153
Epoch 70/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9999 - loss: 3.1318e-04 - val_accuracy: 0.9995 - val_loss: 0.0151
Epoch 71/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 2.6339e-04 - val_accuracy: 0.9994 - val_loss: 0.0160
Epoch 72/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 1.0000 - loss: 2.0402e-04 - val_accuracy: 0.9994 - val_loss: 0.0154
Epoch 73/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 1.0000 - loss: 3.1165e-04 - val_accuracy: 0.9995 - val_loss: 0.0156
Epoch 74/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 2.6172e-04 - val_accuracy: 0.9994 - val_loss: 0.0151
Epoch 75/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9999 - loss: 2.3755e-04 - val_accuracy: 0.9994 - val_loss: 0.0158
Epoch 76/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 1.8717e-04 - val_accuracy: 0.9995 - val_loss: 0.0148
Epoch 77/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 1.0000 - loss: 2.3692e-04 - val_accuracy: 0.9994 - val_loss: 0.0151
Epoch 78/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 2.2146e-04 - val_accuracy: 0.9994 - val_loss: 0.0152
Epoch 79/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 2.3305e-04 - val_accuracy: 0.9993 - val_loss: 0.0159
Epoch 80/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 1.0000 - loss: 2.0968e-04 - val_accuracy: 0.9994 - val_loss: 0.0149
Epoch 81/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.4468e-04 - val_accuracy: 0.9994 - val_loss: 0.0148
Epoch 82/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.5725e-04 - val_accuracy: 0.9994 - val_loss: 0.0156
Epoch 83/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 1.0000 - loss: 1.8126e-04 - val_accuracy: 0.9994 - val_loss: 0.0153
Epoch 84/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 1.0000 - loss: 1.9953e-04 - val_accuracy: 0.9994 - val_loss: 0.0149
Epoch 85/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 1.3084e-04 - val_accuracy: 0.9995 - val_loss: 0.0160
Epoch 86/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.8522e-04 - val_accuracy: 0.9995 - val_loss: 0.0160
Epoch 87/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9999 - loss: 2.4285e-04 - val_accuracy: 0.9994 - val_loss: 0.0157
Epoch 88/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 1.0000 - loss: 1.5993e-04 - val_accuracy: 0.9994 - val_loss: 0.0155
Epoch 89/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 2.7561e-04 - val_accuracy: 0.9994 - val_loss: 0.0154
Epoch 90/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.8497e-04 - val_accuracy: 0.9995 - val_loss: 0.0153
Epoch 91/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 1.0000 - loss: 1.3737e-04 - val_accuracy: 0.9995 - val_loss: 0.0158
Epoch 92/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.4414e-04 - val_accuracy: 0.9994 - val_loss: 0.0151
Epoch 93/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 1.7209e-04 - val_accuracy: 0.9994 - val_loss: 0.0150
Epoch 94/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 1.0000 - loss: 1.2174e-04 - val_accuracy: 0.9995 - val_loss: 0.0152
Epoch 95/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 1.0000 - loss: 1.5109e-04 - val_accuracy: 0.9994 - val_loss: 0.0155
Epoch 96/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 1.1380e-04 - val_accuracy: 0.9994 - val_loss: 0.0156
Epoch 97/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 1.3130e-04 - val_accuracy: 0.9994 - val_loss: 0.0156
Epoch 98/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 1.0000 - loss: 1.1992e-04 - val_accuracy: 0.9994 - val_loss: 0.0156
Epoch 99/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 1.2551e-04 - val_accuracy: 0.9995 - val_loss: 0.0154
Epoch 100/100
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 1.0000 - loss: 1.3417e-04 - val_accuracy: 0.9994 - val_loss: 0.0156

In [51]:
y_pred_proba3 = model3.predict(X_test_scaled)
y_pred3 = (y_pred_proba3 > 0.5).astype(int)

print("Model 3 (ReLU + RMSprop, 100 epochs)")
print("Accuracy:", accuracy_score(y_test, y_pred3))
print("Precision:", precision_score(y_test, y_pred3))
print("Recall:", recall_score(y_test, y_pred3))
print("F1 Score:", f1_score(y_test, y_pred3))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred3))

1774/1774 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step
Model 3 (ReLU + RMSprop, 100 epochs)
Accuracy: 0.9992598597257957
Precision: 0.7849462365591398
Recall: 0.7684210526315789
F1 Score: 0.776595744680851

Confusion Matrix:
[[56631    20]
 [   22    73]]

In [52]:
model4 = keras.Sequential([
    keras.layers.Input(shape=(X_tr_smote.shape[1],)),
    keras.layers.Dense(64, activation='sigmoid'),
    keras.layers.Dense(32, activation='sigmoid'),
    keras.layers.Dense(1, activation='sigmoid')
])

model4.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history4 = model4.fit(
    X_tr_smote, y_tr_smote,
    validation_data=(X_val, y_val),
    epochs=20,
    batch_size=512
)

Epoch 1/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.9387 - loss: 0.1653 - val_accuracy: 0.9630 - val_loss: 0.0978
Epoch 2/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9666 - loss: 0.0793 - val_accuracy: 0.9788 - val_loss: 0.0561
Epoch 3/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9833 - loss: 0.0465 - val_accuracy: 0.9833 - val_loss: 0.0462
Epoch 4/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9949 - loss: 0.0227 - val_accuracy: 0.9928 - val_loss: 0.0217
Epoch 5/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9972 - loss: 0.0132 - val_accuracy: 0.9968 - val_loss: 0.0122
Epoch 6/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9982 - loss: 0.0093 - val_accuracy: 0.9971 - val_loss: 0.0109
Epoch 7/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9987 - loss: 0.0072 - val_accuracy: 0.9978 - val_loss: 0.0096
Epoch 8/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9989 - loss: 0.0061 - val_accuracy: 0.9983 - val_loss: 0.0083
Epoch 9/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9991 - loss: 0.0052 - val_accuracy: 0.9980 - val_loss: 0.0093
Epoch 10/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9993 - loss: 0.0045 - val_accuracy: 0.9987 - val_loss: 0.0076
Epoch 11/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9993 - loss: 0.0040 - val_accuracy: 0.9990 - val_loss: 0.0072
Epoch 12/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9995 - loss: 0.0035 - val_accuracy: 0.9987 - val_loss: 0.0076
Epoch 13/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9995 - loss: 0.0031 - val_accuracy: 0.9989 - val_loss: 0.0068
Epoch 14/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9996 - loss: 0.0025 - val_accuracy: 0.9990 - val_loss: 0.0065
Epoch 15/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9997 - loss: 0.0019 - val_accuracy: 0.9988 - val_loss: 0.0071
Epoch 16/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9997 - loss: 0.0016 - val_accuracy: 0.9987 - val_loss: 0.0072
Epoch 17/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 0.0014 - val_accuracy: 0.9990 - val_loss: 0.0066
Epoch 18/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 0.9991 - val_loss: 0.0066
Epoch 19/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9990 - val_loss: 0.0068
Epoch 20/20
709/709 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9998 - loss: 0.0010 - val_accuracy: 0.9990 - val_loss: 0.0071

In [53]:
y_pred_proba4 = model4.predict(X_test_scaled)
y_pred4 = (y_pred_proba4 > 0.5).astype(int)

print("Model 4 (Sigmoid + Adam, 20 epochs)")
print("Accuracy:", accuracy_score(y_test, y_pred4))
print("Precision:", precision_score(y_test, y_pred4))
print("Recall:", recall_score(y_test, y_pred4))
print("F1 Score:", f1_score(y_test, y_pred4))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred4))

1774/1774 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
Model 4 (Sigmoid + Adam, 20 epochs)
Accuracy: 0.9989250343636555
Precision: 0.6491228070175439
Recall: 0.7789473684210526
F1 Score: 0.7081339712918661

Confusion Matrix:
[[56611    40]
 [   21    74]]

In [55]:
comparison_data = {
    'Model': ['Model 1', 'Model 2', 'Model 3', 'Model 4'],
    'Activation': ['ReLU', 'Tanh', 'ReLU', 'Sigmoid'],
    'Optimizer': ['Adam', 'SGD', 'RMSprop', 'Adam'],
    'Epochs': [50, 50, 100, 20],
    'Accuracy': [0.9993, 0.9929, 0.9993, 0.9989],
    'Precision': [0.7895, 0.1716, 0.7849, 0.6491],
    'Recall': [0.7895, 0.8526, 0.7684, 0.7789],
    'F1 Score': [0.7895, 0.2857, 0.7766, 0.7081]
}

import pandas as pd
comparison_df = pd.DataFrame(comparison_data)
comparison_df.sort_values('F1 Score', ascending=False)

     Model Activation Optimizer  Epochs  Accuracy  Precision  Recall  F1 Score
0  Model 1       ReLU      Adam      50    0.9993     0.7895  0.7895    0.7895
2  Model 3       ReLU   RMSprop     100    0.9993     0.7849  0.7684    0.7766
3  Model 4    Sigmoid      Adam      20    0.9989     0.6491  0.7789    0.7081
1  Model 2       Tanh       SGD      50    0.9929     0.1716  0.8526    0.2857

In [57]:
sample_df = pd.DataFrame({
    'Actual Class': y_test.values[:15],
    'Predicted Class': y_pred.flatten()[:15],       # <- flatten() add kiya
    'Predicted Probability': y_pred_proba.flatten()[:15]
})
sample_df['Actual Class'] = sample_df['Actual Class'].map({0: 'Legitimate', 1: 'Fraud'})
sample_df['Predicted Class'] = sample_df['Predicted Class'].map({0: 'Legitimate', 1: 'Fraud'})
sample_df

   Actual Class Predicted Class  Predicted Probability
0    Legitimate      Legitimate           1.939787e-31
1    Legitimate      Legitimate           7.542886e-34
2    Legitimate      Legitimate           0.000000e+00
3    Legitimate      Legitimate           0.000000e+00
4    Legitimate      Legitimate           1.208372e-16
5    Legitimate      Legitimate           7.592465e-31
6    Legitimate      Legitimate           0.000000e+00
7    Legitimate      Legitimate           0.000000e+00
8    Legitimate      Legitimate           0.000000e+00
9    Legitimate      Legitimate           0.000000e+00
10   Legitimate      Legitimate           0.000000e+00
11   Legitimate      Legitimate           0.000000e+00
12   Legitimate      Legitimate           0.000000e+00
13   Legitimate      Legitimate           7.123954e-22
14   Legitimate      Legitimate           0.000000e+00